cfis/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='cfis'
urlpatterns = [
    path('', views.HomeView.as_view()),
    path('news', views.NewsListView.as_view(), name='news_all'),
    path('news/<int:pk>', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/create',
        views.NewsCreateView.as_view(success_url=reverse_lazy('cfis:news_all')), name='news_create'),
    path('news/<int:pk>/update',
        views.NewsUpdateView.as_view(success_url=reverse_lazy('cfis:news_all')), name='news_update'),
    path('news/<int:pk>/delete',
        views.NewsDeleteView.as_view(success_url=reverse_lazy('cfis:news_all')), name='news_delete'),
    path('news_picture/<int:pk>', views.stream_file, name='news_picture'),
    path('news/<int:pk>/comment',
        views.NewsCommentCreateView.as_view(), name='news_comment_create'),
    path('news_comment/<int:pk>/delete',
        views.NewsCommentDeleteView.as_view(success_url=reverse_lazy('cfis')), name='news_comment_delete'),

    path('post', views.PostListView.as_view(), name='all'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/create',
        views.PostCreateView.as_view(success_url=reverse_lazy('cfis:all')), name='post_create'),
    path('post/<int:pk>/update',
        views.PostUpdateView.as_view(success_url=reverse_lazy('cfis:all')), name='post_update'),
    path('post/<int:pk>/delete',
        views.PostDeleteView.as_view(success_url=reverse_lazy('cfis:all')), name='post_delete'),
    path('post_picture/<int:pk>', views.stream_file, name='post_picture'),
    path('post/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='post_favorite'),
    path('post/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='post_unfavorite'),
    path('post/<int:pk>/comment',
        views.PostCommentCreateView.as_view(), name='post_comment_create'),
    path('post_comment/<int:pk>/delete',
        views.PostCommentDeleteView.as_view(success_url=reverse_lazy('cfis')), name='post_comment_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

cfis/templates/cfis/comment_delete.html
{% extends "cfis_footer.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <button type="button" class="btn btn-primary" onclick="javascript: window.history.go(-1);">Cancel</button>
</form>
{% endblock %}

cfis/templates/cfis/main.html
{% extends "cfis_footer.html" %}
{% block content %}
      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-12 col-md-7 col-sm-6 text-center mt-5 pt-5">
            {% if user.is_authenticated %}
                <h1>Hello {{ user }},</h1>
                <p class="lead">welcome to Community For International Students.<br />
                Please check the most recent news and enjoy the conversation with others!</p>
                <br/>
                <br/>
                <br/>
            {% else %}
                <p class="lead">This is an online community for all the international students studying in the Unites States.<br/>
                If you have not registered yet, please sign up. Otherwise, please sign in to enjoy our community.</p>
                <br/>
                <br/>
                <p class="lead">
                  <a class="btn btn-outline-primary" href="{% url 'login' %}?next={% url 'cfis:all' %}" role="button">Sign in</a>
                </p>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="bs-docs-section">

        <div class="row">
          <div class="col-lg-6">
            <div class="page-header">
              <h2 id="containers">Recent News</h2>
            </div>
            <div class="bs-component">
              <div class="jumbotron pt-5 pb-2">
                <h4 class="display-4">{{ news.title | truncatewords:4 }}</h4>
                <hr class="my-4">
                <p class="lead">
                    {{ news.text | truncatewords:50 }}
                <p class="lead pt-3">
                  <a class="btn btn-primary btn-md" href="{% url 'cfis:news_detail'  news.id %}" id="read-more-post-{{ news.id }}" role="button">Read more</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="page-header">
              <h2 id="containers">Recent Post</h2>
            </div>
            <div class="bs-component">
              <div class="jumbotron pt-5 pb-2">
                <h4 class="display-4">{{ post.title | truncatewords:4 }}</h4>
                <hr class="my-4">
                <p class="lead">
                    {{ post.text | truncatewords:50 }}
                <p class="lead pt-3">
                  <a class="btn btn-primary btn-md" href="{% url 'cfis:post_detail'  post.id %}" id="read-more-post-{{ post.id }}" role="button">Read more</a>
                </p>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

cfis/templates/cfis/news_comment_delete.html
{% extends "cfis_footer.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <button type="button" class="btn btn-primary" onclick="javascript: window.history.go(-1);">Cancel</button>
</form>
{% endblock %}

cfis/templates/cfis/news_confirm_delete.html
{% extends "cfis_footer.html" %}
{% block content %}
<h1>Delete News</h1>

<p>Are you sure you want to delete the news: {{ news }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <button type="button" class="btn btn-primary" onclick="javascript: window.history.go(-1);">Cancel</button>
</form>
{% endblock %}

cfis/templates/cfis/news_detail.html
{% extends "cfis_footer.html" %}
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<!-- Title -->
        <h1 class="mt-4">{{ news.title }}</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{ news.owner }}</a>
        </p>
        {% if news.owner == user %}
        <button type="button" class="btn btn-outline-secondary float-right" style="margin-top: 10px;" onclick="location.href='{% url 'cfis:news_delete' news.id %}'">DELETE</button>
        <button type="button" class="btn btn-outline-secondary float-right mr-2" style="margin-top: 10px;" onclick="location.href='{% url 'cfis:news_update' news.id %}'">EDIT</button>
        {% endif %}
        <hr>

        <!-- Date/Time -->
        <p>Posted on {{ news.created_at }}</p>

        <hr>

        <!-- Preview Image -->
        {% if news.content_type %}
        <img class="card-img-top" src="{% url 'cfis:news_picture' news.id %}" alt="img-{{ news.title }}">
        <hr>
        {% endif %}

        <!-- Post Content -->
        {{ news.text | safe  }}
        <br /><br />

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            {% load crispy_forms_tags %}
            <form method="post" action="{% url 'cfis:news_comment_create' news.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
              <div class="form-group">
              </div>
              <input type="submit" class="btn btn-primary" value="Submit">
            </form>
          </div>
        </div>

        {% for comment in comments %}
        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
                <h5 class="mt-0">{{ comment.owner }} <small class="text-muted">({{ comment.updated_at|naturaltime }})</small></h5>
                {{ comment.text }} <br />
                {% if user == comment.owner %}
                    <a href="{% url 'cfis:news_comment_delete' comment.id %}"><i class="fa fa-trash">delete</i></a>
                {% endif %}
            </div>
        </div>
        {% endfor %}

{% endblock %}

cfis/templates/cfis/news_form.html
{% extends "cfis_footer.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'cfis:all' %}';return false;">
  </form>
</p>
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

cfis/templates/cfis/news_list.html
{% extends "cfis_footer.html" %}
{% block content %}
<div class="row">
    <div id="main-div" class="col-md-8">
        <h1>News</h1>
        <a href="{% url 'cfis:news_create' %}" class="float-right"><button type="button" class="btn btn-outline-primary">Add News</button></a>
        <br /><br />
        {% if news_list %}
        {% for p in news_list %}
            <div id="post-card-{{ p.id }}" class="card mb-4">
                {% if p.picture %}
                <img class="card-img-top" src="{% url 'cfis:news_picture' p.id %}" alt="Card image cap">
                {% endif %}
                <div class="card-body">
                    <h2 class="card-title" onclick="javascript: window.location='{% url 'cfis:news_detail'  p.id %}'" style="cursor: pointer">{{ p.title }}</h2>
                    <p class="card-text">{{ p.text | truncatewords:50 }}</p>
                    <a href="{% url 'cfis:news_detail'  p.id %}" id="read-more-post-{{ p.id }}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    {{ p.created_at }} by
                    <a href="#">{{ p.owner }} </a>
                </div>
            </div>
        {% endfor %}
        {% else %}
            <h3>No post</h3>
        {% endif %}
    </div>
    <div id="side-div" class="col-md-4" onclick="javascript: location.href='http://zacklim.pythonanywhere.com/cfis/news/6'" style="cursor: pointer">
        <div class="card">
            <h3 class="card-header">Hot News</h3>
            <div class="card-body">
                <h5 class="card-title">Coronavirus Diaries: My Green Card Interview Was Canceled...</h5>
                <h6 class="card-subtitle text-muted">Posted by zacklim</h6>
            </div>
            <img style="height: 200px; width: 100%; display: block;" src="/cfis/news_picture/6" alt="Card image">
            <div class="card-body">
                <p class="card-text">Coronavirus Diaries is a series of dispatches exploring how the coronavirus is affecting people’s lives. For the latest public health information, please refer to the Centers for...</p>
            </div>
            <div class="card-footer text-muted">
                April 16, 2020, 12:57 p.m.
            </div>
        </div>
    </div>
</div>
{% endblock %}

cfis/templates/cfis/post_comment_delete.html
{% extends "cfis_footer.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <button type="button" class="btn btn-primary" onclick="javascript: window.history.go(-1);">Cancel</button>
</form>
{% endblock %}

cfis/templates/cfis/post_confirm_delete.html
{% extends "cfis_footer.html" %}
{% block content %}
<h1>Delete Post</h1>

<p>Are you sure you want to delete the news: {{ post }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <button type="button" class="btn btn-primary" onclick="javascript: window.history.go(-1);">Cancel</button>
</form>
{% endblock %}

cfis/templates/cfis/post_detail.html
{% extends "cfis_footer.html" %}
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{ post.owner }}</a>
        </p>
        {% if post.owner == user %}
        <button type="button" class="btn btn-outline-secondary float-right" style="margin-top: 10px;" onclick="location.href='{% url 'cfis:post_delete' post.id %}'">DELETE</button>
        <button type="button" class="btn btn-outline-secondary float-right mr-2" style="margin-top: 10px;" onclick="location.href='{% url 'cfis:post_update' post.id %}'">EDIT</button>
        {% endif %}
        <hr>

        <!-- Date/Time -->
        <p>Posted on {{ post.created_at }}</p>

        <hr>


        <!-- Post Content -->
        {{ post.text | linebreaks  }}
        <br /><br />
        <p>
            {% for tag in post.tags.all %}
                #{{ tag.name }}
            {% endfor %}
        </p>
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            {% load crispy_forms_tags %}
            <form method="post" action="{% url 'cfis:post_comment_create' post.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
              <div class="form-group">
              </div>
              <input type="submit" class="btn btn-primary" value="Submit">
            </form>
          </div>
        </div>

        {% for comment in comments %}
        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
                <h5 class="mt-0">{{ comment.owner }} <small class="text-muted">({{ comment.updated_at|naturaltime }})</small></h5>
                {{ comment.text }} <br />
                {% if user == comment.owner %}
                    <a href="{% url 'cfis:post_comment_delete' comment.id %}"><i class="fa fa-trash">delete</i></a>
                {% endif %}
            </div>
        </div>
        {% endfor %}

{% endblock %}

cfis/templates/cfis/post_form.html
{% extends "cfis_footer.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'cfis:all' %}';return false;">
  </form>
</p>
<script>
{% endblock %}

cfis/templates/cfis/post_list.html
{% extends "cfis_footer.html" %}
{% block content %}
<div class="row">
    <div id="main-div" class="col-md-8">
        <h1>Free Board</h1>
        <a href="{% url 'cfis:post_create' %}" class="float-right"><button type="button" class="btn btn-outline-primary">Add Post</button></a>
        <br /><br />
        {% if post_list %}
        {% for p in post_list %}
            <div id="post-card-{{ p.id }}" class="card mb-4">
                <div class="card-body">
                <!-- <div class="card-body" onclick="javascript: window.location='{% url 'cfis:post_detail'  p.id %}'" style="cursor: pointer"> -->
                    {% if p.category %}
                    <span class="badge badge-primary float-right mt-1">{{ p.category }}</span>
                    {% else %}
                    <span class="badge badge-primary float-right mt-1">Others</span>
                    {% endif %}
                    <h4 class="card-title text-dark" onclick="javascript: window.location='{% url 'cfis:post_detail'  p.id %}'" style="cursor: pointer">{{ p.title }}</h4>
                    <h6 class="font-weight-light">{{ p.created_at }} by {{ p.owner }}</h6>
                </div>
            </div>
        {% endfor %}
        {% else %}
            <h3>No post</h3>
        {% endif %}
    </div>
    <div id="side-div" class="col-md-4" onclick="javascript: location.href='http://zacklim.pythonanywhere.com/cfis/post/5'" style="cursor: pointer">
        <div class="card">
            <h3 class="card-header">Hot News</h3>
            <div class="card-body">
                <h5 class="card-title">Question about OPT</h5>
                <h6 class="card-subtitle text-muted">Posted by samkim</h6>
            </div>
            <div class="card-body">
                <p class="card-text">Hello I am applying for OPT in a couple of days. Is USCIS still working on this? Please let me know if anyone....</p>
            </div>
            <div class="card-footer text-muted">
                April 20, 2020, 1:25 p.m.
            </div>
        </div>
    </div>
</div>
<script>
function favPost(url, thing_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+thing_id).toggle();
        $("#favorite_star_"+thing_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}